package com.libreshockwave.player.cast;

import com.libreshockwave.font.BitmapFont;
import com.libreshockwave.font.TtfBitmapRasterizer;

import java.util.HashMap;
import java.util.Map;
import java.util.function.Supplier;

/**
 * Embedded Mac system fonts for Director movie compatibility.
 * Director movies authored on Mac reference system fonts (Geneva, Chicago, Monaco, etc.)
 * that aren't available on Windows or in WASM. This bundle provides bitmap font TTFs
 * converted from classic Mac OS bitmap fonts, rasterized via TtfBitmapRasterizer
 * (pure Java, TeaVM-compatible — no AWT dependency).
 *
 * Font bytes are embedded as Java byte arrays (generated by sdk-fonts module)
 * to avoid ClassLoader.getResourceAsStream() which is not available in TeaVM WASM.
 *
 * Bold variants are handled the same way as WindowsFontBundle: e.g., EspySansBold
 * is the bold variant of EspySans, not a separate font family.
 *
 * Source: https://github.com/jcs/classic-mac-fonts
 */
public class MacFontBundle {

    /**
     * Font family definition: regular sizes, bold file prefix (null if no bold variant),
     * and bold sizes.
     */
    private static class FontFamily {
        final String filePrefix;       // e.g., "Geneva"
        final int[] sizes;             // available regular sizes
        final String boldFilePrefix;   // e.g., "EspySansBold", null if no bold variant
        final int[] boldSizes;         // available bold sizes (null if no bold)

        FontFamily(String filePrefix, int[] sizes, String boldFilePrefix, int[] boldSizes) {
            this.filePrefix = filePrefix;
            this.sizes = sizes;
            this.boldFilePrefix = boldFilePrefix;
            this.boldSizes = boldSizes;
        }

        FontFamily(String filePrefix, int[] sizes) {
            this(filePrefix, sizes, null, null);
        }
    }

    /** Available Mac font families keyed by lowercase font name */
    private static final Map<String, FontFamily> FONT_FAMILIES = new HashMap<>();
    static {
        FONT_FAMILIES.put("geneva",    new FontFamily("Geneva",    new int[]{9, 10, 12, 14, 18, 20}));
        FONT_FAMILIES.put("chicago",   new FontFamily("Chicago",   new int[]{12}));
        FONT_FAMILIES.put("monaco",    new FontFamily("Monaco",    new int[]{9, 12}));
        FONT_FAMILIES.put("helvetica", new FontFamily("Helvetica", new int[]{9, 10, 12, 14, 18, 24}));
        FONT_FAMILIES.put("courier",   new FontFamily("Courier",   new int[]{9, 10, 12, 14, 18, 24}));
        FONT_FAMILIES.put("times",     new FontFamily("Times",     new int[]{9, 10, 12, 14, 18, 24}));
        FONT_FAMILIES.put("palatino",  new FontFamily("Palatino",  new int[]{10, 12, 14, 18, 24}));
        FONT_FAMILIES.put("espysans",  new FontFamily("EspySans",  new int[]{9, 10, 12, 14, 16},
                                                       "EspySansBold", new int[]{9, 10, 12, 14, 16}));
        FONT_FAMILIES.put("espyserif", new FontFamily("EspySerif", new int[]{10, 12, 14, 16},
                                                       "EspySerifBold", new int[]{10, 12, 14, 16}));
    }

    /**
     * Windows→Mac font name mappings.
     * Director movies may reference Windows font names (from XMED section 0008)
     * that need to be mapped to their Mac equivalents.
     */
    private static final Map<String, String> FONT_ALIASES = Map.of(
            "verdana", "geneva",
            "arial", "helvetica",
            "courier new", "courier",
            "times new roman", "times"
    );

    /**
     * Embedded TTF byte suppliers keyed by "FilePrefix-Size".
     * Maps to sdk-fonts generated classes (no getResourceAsStream needed).
     */
    private static final Map<String, Supplier<byte[]>> TTF_DATA = new HashMap<>();
    static {
        TTF_DATA.put("Geneva-9",  com.libreshockwave.fonts.mac.Geneva_9::getData);
        TTF_DATA.put("Geneva-10", com.libreshockwave.fonts.mac.Geneva_10::getData);
        TTF_DATA.put("Geneva-12", com.libreshockwave.fonts.mac.Geneva_12::getData);
        TTF_DATA.put("Geneva-14", com.libreshockwave.fonts.mac.Geneva_14::getData);
        TTF_DATA.put("Geneva-18", com.libreshockwave.fonts.mac.Geneva_18::getData);
        TTF_DATA.put("Geneva-20", com.libreshockwave.fonts.mac.Geneva_20::getData);
        TTF_DATA.put("Chicago-12", com.libreshockwave.fonts.mac.Chicago_12::getData);
        TTF_DATA.put("Monaco-9",  com.libreshockwave.fonts.mac.Monaco_9::getData);
        TTF_DATA.put("Monaco-12", com.libreshockwave.fonts.mac.Monaco_12::getData);
        TTF_DATA.put("Helvetica-9",  com.libreshockwave.fonts.mac.Helvetica_9::getData);
        TTF_DATA.put("Helvetica-10", com.libreshockwave.fonts.mac.Helvetica_10::getData);
        TTF_DATA.put("Helvetica-12", com.libreshockwave.fonts.mac.Helvetica_12::getData);
        TTF_DATA.put("Helvetica-14", com.libreshockwave.fonts.mac.Helvetica_14::getData);
        TTF_DATA.put("Helvetica-18", com.libreshockwave.fonts.mac.Helvetica_18::getData);
        TTF_DATA.put("Helvetica-24", com.libreshockwave.fonts.mac.Helvetica_24::getData);
        TTF_DATA.put("Courier-9",  com.libreshockwave.fonts.mac.Courier_9::getData);
        TTF_DATA.put("Courier-10", com.libreshockwave.fonts.mac.Courier_10::getData);
        TTF_DATA.put("Courier-12", com.libreshockwave.fonts.mac.Courier_12::getData);
        TTF_DATA.put("Courier-14", com.libreshockwave.fonts.mac.Courier_14::getData);
        TTF_DATA.put("Courier-18", com.libreshockwave.fonts.mac.Courier_18::getData);
        TTF_DATA.put("Courier-24", com.libreshockwave.fonts.mac.Courier_24::getData);
        TTF_DATA.put("Times-9",  com.libreshockwave.fonts.mac.Times_9::getData);
        TTF_DATA.put("Times-10", com.libreshockwave.fonts.mac.Times_10::getData);
        TTF_DATA.put("Times-12", com.libreshockwave.fonts.mac.Times_12::getData);
        TTF_DATA.put("Times-14", com.libreshockwave.fonts.mac.Times_14::getData);
        TTF_DATA.put("Times-18", com.libreshockwave.fonts.mac.Times_18::getData);
        TTF_DATA.put("Times-24", com.libreshockwave.fonts.mac.Times_24::getData);
        TTF_DATA.put("Palatino-10", com.libreshockwave.fonts.mac.Palatino_10::getData);
        TTF_DATA.put("Palatino-12", com.libreshockwave.fonts.mac.Palatino_12::getData);
        TTF_DATA.put("Palatino-14", com.libreshockwave.fonts.mac.Palatino_14::getData);
        TTF_DATA.put("Palatino-18", com.libreshockwave.fonts.mac.Palatino_18::getData);
        TTF_DATA.put("Palatino-24", com.libreshockwave.fonts.mac.Palatino_24::getData);
        TTF_DATA.put("EspySans-9",  com.libreshockwave.fonts.mac.EspySans_9::getData);
        TTF_DATA.put("EspySans-10", com.libreshockwave.fonts.mac.EspySans_10::getData);
        TTF_DATA.put("EspySans-12", com.libreshockwave.fonts.mac.EspySans_12::getData);
        TTF_DATA.put("EspySans-14", com.libreshockwave.fonts.mac.EspySans_14::getData);
        TTF_DATA.put("EspySans-16", com.libreshockwave.fonts.mac.EspySans_16::getData);
        TTF_DATA.put("EspySansBold-9",  com.libreshockwave.fonts.mac.EspySansBold_9::getData);
        TTF_DATA.put("EspySansBold-10", com.libreshockwave.fonts.mac.EspySansBold_10::getData);
        TTF_DATA.put("EspySansBold-12", com.libreshockwave.fonts.mac.EspySansBold_12::getData);
        TTF_DATA.put("EspySansBold-14", com.libreshockwave.fonts.mac.EspySansBold_14::getData);
        TTF_DATA.put("EspySansBold-16", com.libreshockwave.fonts.mac.EspySansBold_16::getData);
        TTF_DATA.put("EspySerif-10", com.libreshockwave.fonts.mac.EspySerif_10::getData);
        TTF_DATA.put("EspySerif-12", com.libreshockwave.fonts.mac.EspySerif_12::getData);
        TTF_DATA.put("EspySerif-14", com.libreshockwave.fonts.mac.EspySerif_14::getData);
        TTF_DATA.put("EspySerif-16", com.libreshockwave.fonts.mac.EspySerif_16::getData);
        TTF_DATA.put("EspySerifBold-10", com.libreshockwave.fonts.mac.EspySerifBold_10::getData);
        TTF_DATA.put("EspySerifBold-12", com.libreshockwave.fonts.mac.EspySerifBold_12::getData);
        TTF_DATA.put("EspySerifBold-14", com.libreshockwave.fonts.mac.EspySerifBold_14::getData);
        TTF_DATA.put("EspySerifBold-16", com.libreshockwave.fonts.mac.EspySerifBold_16::getData);
    }

    private static volatile boolean initialized = false;

    /** Cache: "fontkey:size:bold" -> rasterized BitmapFont */
    private static final Map<String, BitmapFont> cache = new HashMap<>();

    /**
     * Load all bundled Mac fonts and register them in FontRegistry.
     * Safe to call multiple times — only loads once.
     */
    public static void initialize() {
        if (initialized) return;
        initialized = true;

        for (var entry : FONT_FAMILIES.entrySet()) {
            String fontKey = entry.getKey();
            FontFamily family = entry.getValue();
            for (int size : family.sizes) {
                BitmapFont font = loadTtf(family.filePrefix, size, fontKey);
                if (font != null) {
                    FontRegistry.registerBitmapFont(fontKey, size, font);
                }
            }
        }
    }

    /**
     * Try to load a specific Mac font at the given size and style.
     * Consistent with WindowsFontBundle.getFont() signature.
     *
     * @param fontName font name (e.g., "Geneva", "EspySans")
     * @param fontSize target pixel size
     * @param bold true for bold variant
     * @param italic true for italic variant (not yet supported for Mac fonts)
     * @return BitmapFont, or null if not available
     */
    public static BitmapFont getFont(String fontName, int fontSize, boolean bold, boolean italic) {
        if (fontName == null) return null;
        String key = fontName.toLowerCase();

        // Map Windows font names to Mac equivalents
        String mapped = FONT_ALIASES.get(key);
        if (mapped != null) key = mapped;

        FontFamily family = FONT_FAMILIES.get(key);
        if (family == null) return null;

        // Select variant and sizes
        String filePrefix;
        int[] sizes;
        if (bold && family.boldFilePrefix != null) {
            filePrefix = family.boldFilePrefix;
            sizes = family.boldSizes;
        } else {
            filePrefix = family.filePrefix;
            sizes = family.sizes;
        }

        // Find best matching size
        int bestSize = findBestSize(sizes, fontSize);
        if (bestSize <= 0) return null;

        // Check cache
        String cacheKey = key + ":" + bestSize + ":" + (bold ? "bold" : "regular");
        BitmapFont cached = cache.get(cacheKey);
        if (cached != null) return cached;

        // Load on demand
        BitmapFont font = loadTtf(filePrefix, bestSize, key);
        if (font != null) {
            cache.put(cacheKey, font);
        }
        return font;
    }

    /** Backward-compatible overload without bold/italic. */
    public static BitmapFont getFont(String fontName, int fontSize) {
        return getFont(fontName, fontSize, false, false);
    }

    /**
     * Check if a font name matches a bundled Mac font.
     */
    public static boolean hasMacFont(String fontName) {
        if (fontName == null) return false;
        String key = fontName.toLowerCase();
        String mapped = FONT_ALIASES.get(key);
        if (mapped != null) key = mapped;
        return FONT_FAMILIES.containsKey(key);
    }

    /**
     * Check if a specific bold variant exists for the font.
     */
    public static boolean hasBoldVariant(String fontName) {
        if (fontName == null) return false;
        String key = fontName.toLowerCase();
        String mapped = FONT_ALIASES.get(key);
        if (mapped != null) key = mapped;
        FontFamily family = FONT_FAMILIES.get(key);
        return family != null && family.boldFilePrefix != null;
    }

    private static BitmapFont loadTtf(String filePrefix, int size, String fontKey) {
        String dataKey = filePrefix + "-" + size;
        Supplier<byte[]> supplier = TTF_DATA.get(dataKey);
        if (supplier == null) return null;
        byte[] ttfBytes = supplier.get();
        if (ttfBytes == null) return null;
        return TtfBitmapRasterizer.rasterize(ttfBytes, size, fontKey);
    }

    private static int findBestSize(int[] available, int requested) {
        // Prefer exact match
        for (int s : available) {
            if (s == requested) return s;
        }
        // Find closest size
        int best = -1;
        int bestDiff = Integer.MAX_VALUE;
        for (int s : available) {
            int diff = Math.abs(s - requested);
            if (diff < bestDiff) {
                bestDiff = diff;
                best = s;
            }
        }
        return best;
    }
}
