package com.libreshockwave.player.cast;

import com.libreshockwave.font.BitmapFont;
import com.libreshockwave.font.TtfBitmapRasterizer;

import java.util.HashMap;
import java.util.Map;
import java.util.function.Supplier;

/**
 * Embedded Windows system fonts for Director movie compatibility.
 * Director movies authored on Windows reference system fonts (Verdana, Arial, etc.)
 * that may not be available in WASM. This bundle provides TTF font data that is
 * rasterized via the pure-Java TtfBitmapRasterizer (TeaVM-compatible).
 *
 * Font bytes are embedded as Java byte arrays (generated by sdk-fonts module)
 * to avoid ClassLoader.getResourceAsStream() which is not available in TeaVM WASM.
 *
 * Bold, italic, and bold-italic variants are loaded when available.
 */
public class WindowsFontBundle {

    /**
     * Font variant definition: supplier for raw TTF bytes (lazy-loaded from sdk-fonts).
     */
    private record FontVariants(
        Supplier<byte[]> regular,
        Supplier<byte[]> bold,
        Supplier<byte[]> italic,
        Supplier<byte[]> boldItalic
    ) {
        Supplier<byte[]> get(int idx) {
            return switch (idx) {
                case 1 -> bold;
                case 2 -> italic;
                case 3 -> boldItalic;
                default -> regular;
            };
        }
    }

    /**
     * Available Windows fonts keyed by lowercase font name.
     * Each entry maps to suppliers for {regular, bold, italic, bolditalic} byte arrays.
     */
    private static final Map<String, FontVariants> AVAILABLE_FONTS = new HashMap<>();
    static {
        AVAILABLE_FONTS.put("verdana", new FontVariants(
            com.libreshockwave.fonts.windows.Verdana::getData,
            com.libreshockwave.fonts.windows.VerdanaBd::getData,
            com.libreshockwave.fonts.windows.VerdanaIt::getData,
            com.libreshockwave.fonts.windows.VerdanaBdIt::getData));
        AVAILABLE_FONTS.put("arial", new FontVariants(
            com.libreshockwave.fonts.windows.Arial::getData,
            null, null, null));
        AVAILABLE_FONTS.put("courier new", new FontVariants(
            com.libreshockwave.fonts.windows.CourierNew::getData,
            null, null, null));
        AVAILABLE_FONTS.put("times new roman", new FontVariants(
            com.libreshockwave.fonts.windows.TimesNewRoman::getData,
            com.libreshockwave.fonts.windows.TimesNewRomanBd::getData,
            com.libreshockwave.fonts.windows.TimesNewRomanIt::getData,
            com.libreshockwave.fonts.windows.TimesNewRomanBdIt::getData));
    }

    /** Cache: "fontname:size:style" -> rasterized BitmapFont */
    private static final Map<String, BitmapFont> cache = new HashMap<>();

    /**
     * Try to get a Windows font at the given size and style.
     * @param fontName font name (e.g., "Verdana")
     * @param fontSize target pixel size
     * @param bold true for bold variant
     * @param italic true for italic variant
     * @return BitmapFont, or null if not available
     */
    public static BitmapFont getFont(String fontName, int fontSize, boolean bold, boolean italic) {
        if (fontName == null) return null;
        String key = fontName.toLowerCase();

        FontVariants variants = AVAILABLE_FONTS.get(key);
        if (variants == null) return null;

        // Select variant: 0=regular, 1=bold, 2=italic, 3=bolditalic
        int variantIdx = (bold ? 1 : 0) + (italic ? 2 : 0);
        Supplier<byte[]> supplier = variants.get(variantIdx);

        // Fall back to regular if specific variant not available
        if (supplier == null) {
            supplier = variants.regular();
            variantIdx = 0;
        }
        if (supplier == null) return null;

        String cacheKey = key + ":" + fontSize + ":" + variantIdx;
        BitmapFont cached = cache.get(cacheKey);
        if (cached != null) return cached;

        byte[] ttfBytes = supplier.get();
        if (ttfBytes == null) return null;

        BitmapFont font = TtfBitmapRasterizer.rasterize(ttfBytes, fontSize, fontName);
        if (font != null) {
            cache.put(cacheKey, font);
        }
        return font;
    }

    /**
     * Check if a font name has a Windows TTF available.
     */
    public static boolean hasWindowsFont(String fontName) {
        if (fontName == null) return false;
        return AVAILABLE_FONTS.containsKey(fontName.toLowerCase());
    }

    /**
     * Check if a specific bold variant exists for the font.
     */
    public static boolean hasBoldVariant(String fontName) {
        if (fontName == null) return false;
        FontVariants variants = AVAILABLE_FONTS.get(fontName.toLowerCase());
        return variants != null && variants.bold() != null;
    }
}
